[package]
name = "rift-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
mdns-sd = "0.11"
rift-core = { path = "../rift-core" }
thiserror = "1"
tokio = { version = "1", features = ["rt", "sync"] }
tokio-stream = "0.1"
