[package]
name = "rift-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
rift-core = { path = "../rift-core" }
